# Generated by Django 5.0.5 on 2025-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_soutenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
